# Generated by Django 4.0 on 2021-12-21 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITCompany',
            fields=[
                ('id_company', models.AutoField(db_column='ID_company', primary_key=True, serialize=False)),
                ('foundation_year', models.IntegerField(blank=True, db_column='Foundation_year', null=True)),
                ('specialization', models.CharField(blank=True, db_column='Specialization', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'IT_Company',
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id_founder', models.AutoField(db_column='ID_founder', primary_key=True, serialize=False)),
                ('founder_name', models.CharField(blank=True, db_column='Founder_name', max_length=100)),
                ('career', models.CharField(blank=True, db_column='Career', max_length=1000, null=True)),
                ('id_company', models.ForeignKey(blank=True, db_column='ID_company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.itcompany')),
            ],
            options={
                'db_table': 'Founder',
            },
        ),
    ]
