# Generated by Django 4.0 on 2021-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITCompany',
            fields=[
                ('id_company', models.AutoField(db_column='ID_company', primary_key=True, serialize=False)),
                ('name_company', models.CharField(blank=True, db_column='Name_company', max_length=100)),
                ('foundation_year', models.IntegerField(blank=True, db_column='Foundation_year', null=True)),
                ('specialization', models.CharField(blank=True, db_column='Specialization', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'IT_Company',
            },
        ),
    ]
